name: Docs Check
on:
  pull_request:
  push:
    branches:
    - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
